site_name: 4cities GIS course
site_url: https://ernesmb.github.io/4cities-GIS
repo_url: https://github.com/ernesmb/4cities-GIS
site_author: Ernesto Martínez Becerra
pages:
    - Hello: index.md
    - Intro to GIS: 01_intro.md
    - CARTO office: 02_carto.md
    - QGIS I: 03_qgis.md
    - QGIS II: 04_qgis.md
    - Cloud GIS: 05_cloud.md
    - Geospatial databases: 06_geodb.md
    - Webmapping: 07_webmaps.md

theme:
    name: null
    custom_dir: 'cinder/'