site_name: 4cities GIS course
site_url: https://ernesmb.github.io/4cities-GIS
repo_url: https://github.com/ernesmb/4cities-GIS
site_author: Ernesto Martínez Becerra
pages:
    - Hello: index.md
theme:
    name: null
    custom_dir: 'cinder/'